version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finder-portal-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=abac_finder_portal_super_secret_key_123
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MY_PEER_API_KEY=${MY_PEER_API_KEY:-fp_peer_api_key_xyz_998877}
      - THEIR_PEER_API_KEY=${THEIR_PEER_API_KEY:-10a92f973b4d7b9ba5c0ecbc8f812e62ac22520b0ca8b6a6beeb157cfd0a81e9}
      - SPACE_RESERVE_API_URL=${SPACE_RESERVE_API_URL:-https://spacereserve.malaysiawest.cloudapp.azure.com/spacereserve/api/v1}
      - AZURE_KEY_VAULT_URL=${AZURE_KEY_VAULT_URL}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    volumes:
      - ./backend/prisma:/usr/src/app/prisma
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finder-portal-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
